"""添加或修改字段

Revision ID: 1eef34530d0d
Revises: 
Create Date: 2025-04-13 22:35:09.841860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eef34530d0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary', sa.Column('diary_list_id', sa.Integer(), nullable=False, comment='对应diary_list的id'))
    op.create_unique_constraint(None, 'diary', ['diary_list_id'])
    op.create_foreign_key(None, 'diary', 'diary_list', ['diary_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diary', type_='foreignkey')
    op.drop_constraint(None, 'diary', type_='unique')
    op.drop_column('diary', 'diary_list_id')
    # ### end Alembic commands ###
