"""我的信息合并到models/about_me.py中

Revision ID: c45ecf5bcc1e
Revises: ac7a7a16306d
Create Date: 2025-04-14 13:27:22.856079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45ecf5bcc1e'
down_revision: Union[str, None] = 'ac7a7a16306d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
