"""modified visitor_log model

Revision ID: e3272b03f96c
Revises: 649be773c4f2
Create Date: 2025-04-15 23:57:53.946536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3272b03f96c'
down_revision: Union[str, None] = '649be773c4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitor_log', 'id',
               existing_type=mysql.INTEGER(),
               comment='日志ID',
               existing_comment='日志 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('visitor_log', 'visitor_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='访客唯一ID(如localStorage中的UUID)',
               existing_comment='访客唯一 ID（如 localStorage 中的 UUID）',
               existing_nullable=False)
    op.alter_column('visitor_log', 'ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='IP地址',
               existing_comment='IP 地址',
               existing_nullable=False)
    op.alter_column('visitor_log', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=512),
               existing_comment='访问路径',
               existing_nullable=False)
    op.alter_column('visitor_log', 'referer',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=512),
               existing_comment='来源页面',
               existing_nullable=True)
    op.alter_column('visitor_log', 'user_agent',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=1024),
               existing_comment='User-Agent',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitor_log', 'user_agent',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_comment='User-Agent',
               existing_nullable=True)
    op.alter_column('visitor_log', 'referer',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_comment='来源页面',
               existing_nullable=True)
    op.alter_column('visitor_log', 'path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_comment='访问路径',
               existing_nullable=False)
    op.alter_column('visitor_log', 'ip',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='IP 地址',
               existing_comment='IP地址',
               existing_nullable=False)
    op.alter_column('visitor_log', 'visitor_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               comment='访客唯一 ID（如 localStorage 中的 UUID）',
               existing_comment='访客唯一ID(如localStorage中的UUID)',
               existing_nullable=False)
    op.alter_column('visitor_log', 'id',
               existing_type=mysql.INTEGER(),
               comment='日志 ID',
               existing_comment='日志ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
