"""修复 NoteList 与 Category 关系字段

Revision ID: e96f695fefcc
Revises: 4e0f1303e7fe
Create Date: 2025-04-13 23:26:17.662710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e96f695fefcc'
down_revision: Union[str, None] = '4e0f1303e7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diarylist_tag',
    sa.Column('diary_list_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diary_list_id'], ['diary_list.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('diary_list_id', 'tag_id')
    )
    op.create_table('notelist_tag',
    sa.Column('note_list_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_list_id'], ['note_list.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('note_list_id', 'tag_id')
    )
    op.drop_table('note_tag')
    op.drop_table('diary_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_tag',
    sa.Column('diary_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diary.id'], name='diary_tag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='diary_tag_ibfk_2'),
    sa.PrimaryKeyConstraint('diary_id', 'tag_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('note_tag',
    sa.Column('note_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='note_tag_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='note_tag_ibfk_2'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('notelist_tag')
    op.drop_table('diarylist_tag')
    # ### end Alembic commands ###
